### ISSUE TITLE
Get user's password without echo'ing

### ISSUE THREAD

**Issue by bestchai** [jchenj/ezpass#61]
This module is part of standard library:
https://docs.python.org/3.7/library/getpass.html

HowTo:
https://www.geeksforgeeks.org/getpass-and-getuser-in-python-password-without-echo/

**Comment by jchenj** [comment]
Password input is echoed in interactive mode (see alert below). Is there anything we can do about this? 
`
(ezpass) newac -on jorg2
Creating new account for: jorg2
Enter username: chenchen
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Enter password: pass1234

Account created for: jorg2
(ezpass) `

**Comment by jchenj** [comment]
Closing this issue. Issue #71 opened to address question about echoing in interactive mode
