### ISSUE TITLE
The org notion has to be reflected into command line args

### ISSUE THREAD

**Issue by bestchai** [jchenj/ezpass#66]
-na NEW_ACCOUNT

Actually represents an org. Has to be named appropriately.

**Comment by jchenj** [comment]
The item for -na NEW_ACCOUNT is now solved, so I'm closing this issue. 

Two other command line args should also be clarified around the relationship between orgs & accounts - '-g', '--get-acpass' & '-cp', '--change-acpass' but this will be better handled in the course of Issue #60
